[package]
name = "go-concurrency-patterns-in-rust"
version = "0.1.0"
authors = ["Dan Munckton <dan@cultivatehq.com>"]

[dependencies]
rand = "0.3.15"
chan = "0.1.19"
futures = "0.1.11"
futures-cpupool = "0.1.5"
lazy_static = "0.2.6"
